# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pbs_ifl
else:
    import _pbs_ifl

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


TYPE_ATTR_READONLY = _pbs_ifl.TYPE_ATTR_READONLY
TYPE_ATTR_PUBLIC = _pbs_ifl.TYPE_ATTR_PUBLIC
TYPE_ATTR_INVISIBLE = _pbs_ifl.TYPE_ATTR_INVISIBLE
TYPE_ATTR_ALL = _pbs_ifl.TYPE_ATTR_ALL
ATTR_a = _pbs_ifl.ATTR_a
ATTR_c = _pbs_ifl.ATTR_c
ATTR_e = _pbs_ifl.ATTR_e
ATTR_g = _pbs_ifl.ATTR_g
ATTR_h = _pbs_ifl.ATTR_h
ATTR_j = _pbs_ifl.ATTR_j
ATTR_J = _pbs_ifl.ATTR_J
ATTR_k = _pbs_ifl.ATTR_k
ATTR_l = _pbs_ifl.ATTR_l
ATTR_l_orig = _pbs_ifl.ATTR_l_orig
ATTR_l_acct = _pbs_ifl.ATTR_l_acct
ATTR_m = _pbs_ifl.ATTR_m
ATTR_o = _pbs_ifl.ATTR_o
ATTR_p = _pbs_ifl.ATTR_p
ATTR_q = _pbs_ifl.ATTR_q
ATTR_R = _pbs_ifl.ATTR_R
ATTR_r = _pbs_ifl.ATTR_r
ATTR_u = _pbs_ifl.ATTR_u
ATTR_v = _pbs_ifl.ATTR_v
ATTR_A = _pbs_ifl.ATTR_A
ATTR_M = _pbs_ifl.ATTR_M
ATTR_N = _pbs_ifl.ATTR_N
ATTR_S = _pbs_ifl.ATTR_S
ATTR_array_indices_submitted = _pbs_ifl.ATTR_array_indices_submitted
ATTR_depend = _pbs_ifl.ATTR_depend
ATTR_inter = _pbs_ifl.ATTR_inter
ATTR_sandbox = _pbs_ifl.ATTR_sandbox
ATTR_stagein = _pbs_ifl.ATTR_stagein
ATTR_stageout = _pbs_ifl.ATTR_stageout
ATTR_resvTag = _pbs_ifl.ATTR_resvTag
ATTR_resv_start = _pbs_ifl.ATTR_resv_start
ATTR_resv_end = _pbs_ifl.ATTR_resv_end
ATTR_resv_duration = _pbs_ifl.ATTR_resv_duration
ATTR_resv_state = _pbs_ifl.ATTR_resv_state
ATTR_resv_substate = _pbs_ifl.ATTR_resv_substate
ATTR_resv_job = _pbs_ifl.ATTR_resv_job
ATTR_auth_u = _pbs_ifl.ATTR_auth_u
ATTR_auth_g = _pbs_ifl.ATTR_auth_g
ATTR_auth_h = _pbs_ifl.ATTR_auth_h
ATTR_cred = _pbs_ifl.ATTR_cred
ATTR_nodemux = _pbs_ifl.ATTR_nodemux
ATTR_umask = _pbs_ifl.ATTR_umask
ATTR_block = _pbs_ifl.ATTR_block
ATTR_convert = _pbs_ifl.ATTR_convert
ATTR_DefaultChunk = _pbs_ifl.ATTR_DefaultChunk
ATTR_X11_cookie = _pbs_ifl.ATTR_X11_cookie
ATTR_X11_port = _pbs_ifl.ATTR_X11_port
ATTR_GUI = _pbs_ifl.ATTR_GUI
ATTR_max_run_subjobs = _pbs_ifl.ATTR_max_run_subjobs
ATTR_resv_standing = _pbs_ifl.ATTR_resv_standing
ATTR_resv_count = _pbs_ifl.ATTR_resv_count
ATTR_resv_idx = _pbs_ifl.ATTR_resv_idx
ATTR_resv_rrule = _pbs_ifl.ATTR_resv_rrule
ATTR_resv_execvnodes = _pbs_ifl.ATTR_resv_execvnodes
ATTR_resv_timezone = _pbs_ifl.ATTR_resv_timezone
ATTR_ctime = _pbs_ifl.ATTR_ctime
ATTR_estimated = _pbs_ifl.ATTR_estimated
ATTR_exechost = _pbs_ifl.ATTR_exechost
ATTR_exechost_acct = _pbs_ifl.ATTR_exechost_acct
ATTR_exechost_orig = _pbs_ifl.ATTR_exechost_orig
ATTR_exechost2 = _pbs_ifl.ATTR_exechost2
ATTR_execvnode = _pbs_ifl.ATTR_execvnode
ATTR_execvnode_acct = _pbs_ifl.ATTR_execvnode_acct
ATTR_execvnode_deallocated = _pbs_ifl.ATTR_execvnode_deallocated
ATTR_execvnode_orig = _pbs_ifl.ATTR_execvnode_orig
ATTR_resv_nodes = _pbs_ifl.ATTR_resv_nodes
ATTR_mtime = _pbs_ifl.ATTR_mtime
ATTR_qtime = _pbs_ifl.ATTR_qtime
ATTR_session = _pbs_ifl.ATTR_session
ATTR_jobdir = _pbs_ifl.ATTR_jobdir
ATTR_euser = _pbs_ifl.ATTR_euser
ATTR_egroup = _pbs_ifl.ATTR_egroup
ATTR_project = _pbs_ifl.ATTR_project
ATTR_hashname = _pbs_ifl.ATTR_hashname
ATTR_hopcount = _pbs_ifl.ATTR_hopcount
ATTR_security = _pbs_ifl.ATTR_security
ATTR_sched_hint = _pbs_ifl.ATTR_sched_hint
ATTR_SchedSelect = _pbs_ifl.ATTR_SchedSelect
ATTR_SchedSelect_orig = _pbs_ifl.ATTR_SchedSelect_orig
ATTR_substate = _pbs_ifl.ATTR_substate
ATTR_name = _pbs_ifl.ATTR_name
ATTR_owner = _pbs_ifl.ATTR_owner
ATTR_used = _pbs_ifl.ATTR_used
ATTR_used_acct = _pbs_ifl.ATTR_used_acct
ATTR_used_update = _pbs_ifl.ATTR_used_update
ATTR_relnodes_on_stageout = _pbs_ifl.ATTR_relnodes_on_stageout
ATTR_tolerate_node_failures = _pbs_ifl.ATTR_tolerate_node_failures
ATTR_released = _pbs_ifl.ATTR_released
ATTR_rel_list = _pbs_ifl.ATTR_rel_list
ATTR_state = _pbs_ifl.ATTR_state
ATTR_queue = _pbs_ifl.ATTR_queue
ATTR_resv = _pbs_ifl.ATTR_resv
ATTR_server = _pbs_ifl.ATTR_server
ATTR_maxrun = _pbs_ifl.ATTR_maxrun
ATTR_max_run = _pbs_ifl.ATTR_max_run
ATTR_max_run_res = _pbs_ifl.ATTR_max_run_res
ATTR_max_run_soft = _pbs_ifl.ATTR_max_run_soft
ATTR_max_run_res_soft = _pbs_ifl.ATTR_max_run_res_soft
ATTR_total = _pbs_ifl.ATTR_total
ATTR_comment = _pbs_ifl.ATTR_comment
ATTR_comment_aux = _pbs_ifl.ATTR_comment_aux
ATTR_cookie = _pbs_ifl.ATTR_cookie
ATTR_qrank = _pbs_ifl.ATTR_qrank
ATTR_altid = _pbs_ifl.ATTR_altid
ATTR_altid2 = _pbs_ifl.ATTR_altid2
ATTR_acct_id = _pbs_ifl.ATTR_acct_id
ATTR_array = _pbs_ifl.ATTR_array
ATTR_array_id = _pbs_ifl.ATTR_array_id
ATTR_array_index = _pbs_ifl.ATTR_array_index
ATTR_array_state_count = _pbs_ifl.ATTR_array_state_count
ATTR_array_indices_remaining = _pbs_ifl.ATTR_array_indices_remaining
ATTR_etime = _pbs_ifl.ATTR_etime
ATTR_gridname = _pbs_ifl.ATTR_gridname
ATTR_refresh = _pbs_ifl.ATTR_refresh
ATTR_ReqCredEnable = _pbs_ifl.ATTR_ReqCredEnable
ATTR_ReqCred = _pbs_ifl.ATTR_ReqCred
ATTR_runcount = _pbs_ifl.ATTR_runcount
ATTR_run_version = _pbs_ifl.ATTR_run_version
ATTR_stime = _pbs_ifl.ATTR_stime
ATTR_obittime = _pbs_ifl.ATTR_obittime
ATTR_executable = _pbs_ifl.ATTR_executable
ATTR_Arglist = _pbs_ifl.ATTR_Arglist
ATTR_version = _pbs_ifl.ATTR_version
ATTR_eligible_time = _pbs_ifl.ATTR_eligible_time
ATTR_accrue_type = _pbs_ifl.ATTR_accrue_type
ATTR_sample_starttime = _pbs_ifl.ATTR_sample_starttime
ATTR_job_kill_delay = _pbs_ifl.ATTR_job_kill_delay
ATTR_topjob_ineligible = _pbs_ifl.ATTR_topjob_ineligible
ATTR_submit_host = _pbs_ifl.ATTR_submit_host
ATTR_cred_id = _pbs_ifl.ATTR_cred_id
ATTR_cred_validity = _pbs_ifl.ATTR_cred_validity
ATTR_history_timestamp = _pbs_ifl.ATTR_history_timestamp
ATTR_create_resv_from_job = _pbs_ifl.ATTR_create_resv_from_job
ATTR_stageout_status = _pbs_ifl.ATTR_stageout_status
ATTR_exit_status = _pbs_ifl.ATTR_exit_status
ATTR_submit_arguments = _pbs_ifl.ATTR_submit_arguments
ATTR_resv_name = _pbs_ifl.ATTR_resv_name
ATTR_resv_owner = _pbs_ifl.ATTR_resv_owner
ATTR_resv_Tag = _pbs_ifl.ATTR_resv_Tag
ATTR_resv_ID = _pbs_ifl.ATTR_resv_ID
ATTR_resv_retry = _pbs_ifl.ATTR_resv_retry
ATTR_del_idle_time = _pbs_ifl.ATTR_del_idle_time
ATTR_aclgren = _pbs_ifl.ATTR_aclgren
ATTR_aclgroup = _pbs_ifl.ATTR_aclgroup
ATTR_aclhten = _pbs_ifl.ATTR_aclhten
ATTR_aclhost = _pbs_ifl.ATTR_aclhost
ATTR_aclhostmomsen = _pbs_ifl.ATTR_aclhostmomsen
ATTR_acluren = _pbs_ifl.ATTR_acluren
ATTR_acluser = _pbs_ifl.ATTR_acluser
ATTR_altrouter = _pbs_ifl.ATTR_altrouter
ATTR_chkptmin = _pbs_ifl.ATTR_chkptmin
ATTR_enable = _pbs_ifl.ATTR_enable
ATTR_fromroute = _pbs_ifl.ATTR_fromroute
ATTR_HasNodes = _pbs_ifl.ATTR_HasNodes
ATTR_killdelay = _pbs_ifl.ATTR_killdelay
ATTR_maxgrprun = _pbs_ifl.ATTR_maxgrprun
ATTR_maxgrprunsoft = _pbs_ifl.ATTR_maxgrprunsoft
ATTR_maxque = _pbs_ifl.ATTR_maxque
ATTR_max_queued = _pbs_ifl.ATTR_max_queued
ATTR_max_queued_res = _pbs_ifl.ATTR_max_queued_res
ATTR_queued_jobs_threshold = _pbs_ifl.ATTR_queued_jobs_threshold
ATTR_queued_jobs_threshold_res = _pbs_ifl.ATTR_queued_jobs_threshold_res
ATTR_maxuserrun = _pbs_ifl.ATTR_maxuserrun
ATTR_maxuserrunsoft = _pbs_ifl.ATTR_maxuserrunsoft
ATTR_qtype = _pbs_ifl.ATTR_qtype
ATTR_rescassn = _pbs_ifl.ATTR_rescassn
ATTR_rescdflt = _pbs_ifl.ATTR_rescdflt
ATTR_rescmax = _pbs_ifl.ATTR_rescmax
ATTR_rescmin = _pbs_ifl.ATTR_rescmin
ATTR_rndzretry = _pbs_ifl.ATTR_rndzretry
ATTR_routedest = _pbs_ifl.ATTR_routedest
ATTR_routeheld = _pbs_ifl.ATTR_routeheld
ATTR_routewait = _pbs_ifl.ATTR_routewait
ATTR_routeretry = _pbs_ifl.ATTR_routeretry
ATTR_routelife = _pbs_ifl.ATTR_routelife
ATTR_rsvexpdt = _pbs_ifl.ATTR_rsvexpdt
ATTR_rsvsync = _pbs_ifl.ATTR_rsvsync
ATTR_start = _pbs_ifl.ATTR_start
ATTR_count = _pbs_ifl.ATTR_count
ATTR_number = _pbs_ifl.ATTR_number
ATTR_jobscript_max_size = _pbs_ifl.ATTR_jobscript_max_size
ATTR_fairshare_tree = _pbs_ifl.ATTR_fairshare_tree
ATTR_SvrHost = _pbs_ifl.ATTR_SvrHost
ATTR_aclroot = _pbs_ifl.ATTR_aclroot
ATTR_managers = _pbs_ifl.ATTR_managers
ATTR_dfltque = _pbs_ifl.ATTR_dfltque
ATTR_defnode = _pbs_ifl.ATTR_defnode
ATTR_locsvrs = _pbs_ifl.ATTR_locsvrs
ATTR_logevents = _pbs_ifl.ATTR_logevents
ATTR_logfile = _pbs_ifl.ATTR_logfile
ATTR_mailer = _pbs_ifl.ATTR_mailer
ATTR_mailfrom = _pbs_ifl.ATTR_mailfrom
ATTR_nodepack = _pbs_ifl.ATTR_nodepack
ATTR_nodefailrq = _pbs_ifl.ATTR_nodefailrq
ATTR_operators = _pbs_ifl.ATTR_operators
ATTR_queryother = _pbs_ifl.ATTR_queryother
ATTR_resccost = _pbs_ifl.ATTR_resccost
ATTR_rescavail = _pbs_ifl.ATTR_rescavail
ATTR_resreserved = _pbs_ifl.ATTR_resreserved
ATTR_maxuserres = _pbs_ifl.ATTR_maxuserres
ATTR_maxuserressoft = _pbs_ifl.ATTR_maxuserressoft
ATTR_maxgroupres = _pbs_ifl.ATTR_maxgroupres
ATTR_maxgroupressoft = _pbs_ifl.ATTR_maxgroupressoft
ATTR_maxarraysize = _pbs_ifl.ATTR_maxarraysize
ATTR_PNames = _pbs_ifl.ATTR_PNames
ATTR_schediteration = _pbs_ifl.ATTR_schediteration
ATTR_scheduling = _pbs_ifl.ATTR_scheduling
ATTR_status = _pbs_ifl.ATTR_status
ATTR_syscost = _pbs_ifl.ATTR_syscost
ATTR_FlatUID = _pbs_ifl.ATTR_FlatUID
ATTR_ResvEnable = _pbs_ifl.ATTR_ResvEnable
ATTR_aclResvgren = _pbs_ifl.ATTR_aclResvgren
ATTR_aclResvgroup = _pbs_ifl.ATTR_aclResvgroup
ATTR_aclResvhten = _pbs_ifl.ATTR_aclResvhten
ATTR_aclResvhost = _pbs_ifl.ATTR_aclResvhost
ATTR_aclResvuren = _pbs_ifl.ATTR_aclResvuren
ATTR_aclResvuser = _pbs_ifl.ATTR_aclResvuser
ATTR_NodeGroupEnable = _pbs_ifl.ATTR_NodeGroupEnable
ATTR_NodeGroupKey = _pbs_ifl.ATTR_NodeGroupKey
ATTR_dfltqdelargs = _pbs_ifl.ATTR_dfltqdelargs
ATTR_dfltqsubargs = _pbs_ifl.ATTR_dfltqsubargs
ATTR_rpp_retry = _pbs_ifl.ATTR_rpp_retry
ATTR_rpp_highwater = _pbs_ifl.ATTR_rpp_highwater
ATTR_pbs_license_info = _pbs_ifl.ATTR_pbs_license_info
ATTR_license_min = _pbs_ifl.ATTR_license_min
ATTR_license_max = _pbs_ifl.ATTR_license_max
ATTR_license_linger = _pbs_ifl.ATTR_license_linger
ATTR_license_count = _pbs_ifl.ATTR_license_count
ATTR_job_sort_formula = _pbs_ifl.ATTR_job_sort_formula
ATTR_EligibleTimeEnable = _pbs_ifl.ATTR_EligibleTimeEnable
ATTR_resv_retry_time = _pbs_ifl.ATTR_resv_retry_time
ATTR_resv_retry_init = _pbs_ifl.ATTR_resv_retry_init
ATTR_JobHistoryEnable = _pbs_ifl.ATTR_JobHistoryEnable
ATTR_JobHistoryDuration = _pbs_ifl.ATTR_JobHistoryDuration
ATTR_max_concurrent_prov = _pbs_ifl.ATTR_max_concurrent_prov
ATTR_resv_post_processing = _pbs_ifl.ATTR_resv_post_processing
ATTR_backfill_depth = _pbs_ifl.ATTR_backfill_depth
ATTR_job_requeue_timeout = _pbs_ifl.ATTR_job_requeue_timeout
ATTR_show_hidden_attribs = _pbs_ifl.ATTR_show_hidden_attribs
ATTR_python_restart_max_hooks = _pbs_ifl.ATTR_python_restart_max_hooks
ATTR_python_restart_max_objects = _pbs_ifl.ATTR_python_restart_max_objects
ATTR_python_restart_min_interval = _pbs_ifl.ATTR_python_restart_min_interval
ATTR_power_provisioning = _pbs_ifl.ATTR_power_provisioning
ATTR_sync_mom_hookfiles_timeout = _pbs_ifl.ATTR_sync_mom_hookfiles_timeout
ATTR_max_job_sequence_id = _pbs_ifl.ATTR_max_job_sequence_id
ATTR_has_runjob_hook = _pbs_ifl.ATTR_has_runjob_hook
ATTR_acl_krb_realm_enable = _pbs_ifl.ATTR_acl_krb_realm_enable
ATTR_acl_krb_realms = _pbs_ifl.ATTR_acl_krb_realms
ATTR_acl_krb_submit_realms = _pbs_ifl.ATTR_acl_krb_submit_realms
ATTR_acl_krb_default_realm_enable = _pbs_ifl.ATTR_acl_krb_default_realm_enable
ATTR_acl_krb_default_realm = _pbs_ifl.ATTR_acl_krb_default_realm
ATTR_krb_default_realm = _pbs_ifl.ATTR_krb_default_realm
ATTR_cred_renew_enable = _pbs_ifl.ATTR_cred_renew_enable
ATTR_cred_renew_tool = _pbs_ifl.ATTR_cred_renew_tool
ATTR_cred_renew_period = _pbs_ifl.ATTR_cred_renew_period
ATTR_cred_renew_cache_period = _pbs_ifl.ATTR_cred_renew_cache_period
ATTR_attr_update_period = _pbs_ifl.ATTR_attr_update_period
ATTR_rpp_max_pkt_check = _pbs_ifl.ATTR_rpp_max_pkt_check
ATTR_SchedHost = _pbs_ifl.ATTR_SchedHost
ATTR_sched_cycle_len = _pbs_ifl.ATTR_sched_cycle_len
ATTR_do_not_span_psets = _pbs_ifl.ATTR_do_not_span_psets
ATTR_only_explicit_psets = _pbs_ifl.ATTR_only_explicit_psets
ATTR_sched_preempt_enforce_resumption = _pbs_ifl.ATTR_sched_preempt_enforce_resumption
ATTR_preempt_targets_enable = _pbs_ifl.ATTR_preempt_targets_enable
ATTR_job_sort_formula_threshold = _pbs_ifl.ATTR_job_sort_formula_threshold
ATTR_throughput_mode = _pbs_ifl.ATTR_throughput_mode
ATTR_opt_backfill_fuzzy = _pbs_ifl.ATTR_opt_backfill_fuzzy
ATTR_partition = _pbs_ifl.ATTR_partition
ATTR_sched_priv = _pbs_ifl.ATTR_sched_priv
ATTR_sched_log = _pbs_ifl.ATTR_sched_log
ATTR_sched_user = _pbs_ifl.ATTR_sched_user
ATTR_sched_state = _pbs_ifl.ATTR_sched_state
ATTR_sched_preempt_queue_prio = _pbs_ifl.ATTR_sched_preempt_queue_prio
ATTR_sched_preempt_prio = _pbs_ifl.ATTR_sched_preempt_prio
ATTR_sched_preempt_order = _pbs_ifl.ATTR_sched_preempt_order
ATTR_sched_preempt_sort = _pbs_ifl.ATTR_sched_preempt_sort
ATTR_sched_server_dyn_res_alarm = _pbs_ifl.ATTR_sched_server_dyn_res_alarm
ATTR_job_run_wait = _pbs_ifl.ATTR_job_run_wait
ATTR_NODE_Host = _pbs_ifl.ATTR_NODE_Host
ATTR_NODE_Mom = _pbs_ifl.ATTR_NODE_Mom
ATTR_NODE_Port = _pbs_ifl.ATTR_NODE_Port
ATTR_NODE_state = _pbs_ifl.ATTR_NODE_state
ATTR_NODE_state_aux = _pbs_ifl.ATTR_NODE_state_aux
ATTR_NODE_ntype = _pbs_ifl.ATTR_NODE_ntype
ATTR_NODE_jobs = _pbs_ifl.ATTR_NODE_jobs
ATTR_NODE_resvs = _pbs_ifl.ATTR_NODE_resvs
ATTR_NODE_resv_enable = _pbs_ifl.ATTR_NODE_resv_enable
ATTR_NODE_np = _pbs_ifl.ATTR_NODE_np
ATTR_NODE_pcpus = _pbs_ifl.ATTR_NODE_pcpus
ATTR_NODE_properties = _pbs_ifl.ATTR_NODE_properties
ATTR_NODE_NoMultiNode = _pbs_ifl.ATTR_NODE_NoMultiNode
ATTR_NODE_No_Tasks = _pbs_ifl.ATTR_NODE_No_Tasks
ATTR_NODE_Sharing = _pbs_ifl.ATTR_NODE_Sharing
ATTR_NODE_ProvisionEnable = _pbs_ifl.ATTR_NODE_ProvisionEnable
ATTR_NODE_current_aoe = _pbs_ifl.ATTR_NODE_current_aoe
ATTR_NODE_in_multivnode_host = _pbs_ifl.ATTR_NODE_in_multivnode_host
ATTR_NODE_License = _pbs_ifl.ATTR_NODE_License
ATTR_NODE_LicenseInfo = _pbs_ifl.ATTR_NODE_LicenseInfo
ATTR_NODE_TopologyInfo = _pbs_ifl.ATTR_NODE_TopologyInfo
ATTR_NODE_MaintJobs = _pbs_ifl.ATTR_NODE_MaintJobs
ATTR_NODE_VnodePool = _pbs_ifl.ATTR_NODE_VnodePool
ATTR_NODE_current_eoe = _pbs_ifl.ATTR_NODE_current_eoe
ATTR_NODE_power_provisioning = _pbs_ifl.ATTR_NODE_power_provisioning
ATTR_NODE_poweroff_eligible = _pbs_ifl.ATTR_NODE_poweroff_eligible
ATTR_NODE_last_state_change_time = _pbs_ifl.ATTR_NODE_last_state_change_time
ATTR_NODE_last_used_time = _pbs_ifl.ATTR_NODE_last_used_time
ND_RESC_LicSignature = _pbs_ifl.ND_RESC_LicSignature
ATTR_RESC_TYPE = _pbs_ifl.ATTR_RESC_TYPE
ATTR_RESC_FLAG = _pbs_ifl.ATTR_RESC_FLAG
CHECKPOINT_UNSPECIFIED = _pbs_ifl.CHECKPOINT_UNSPECIFIED
NO_HOLD = _pbs_ifl.NO_HOLD
NO_JOIN = _pbs_ifl.NO_JOIN
NO_KEEP = _pbs_ifl.NO_KEEP
MAIL_AT_ABORT = _pbs_ifl.MAIL_AT_ABORT
USER_HOLD = _pbs_ifl.USER_HOLD
OTHER_HOLD = _pbs_ifl.OTHER_HOLD
SYSTEM_HOLD = _pbs_ifl.SYSTEM_HOLD
BAD_PASSWORD_HOLD = _pbs_ifl.BAD_PASSWORD_HOLD
MGR_CMD_NONE = _pbs_ifl.MGR_CMD_NONE
MGR_CMD_CREATE = _pbs_ifl.MGR_CMD_CREATE
MGR_CMD_DELETE = _pbs_ifl.MGR_CMD_DELETE
MGR_CMD_SET = _pbs_ifl.MGR_CMD_SET
MGR_CMD_UNSET = _pbs_ifl.MGR_CMD_UNSET
MGR_CMD_LIST = _pbs_ifl.MGR_CMD_LIST
MGR_CMD_PRINT = _pbs_ifl.MGR_CMD_PRINT
MGR_CMD_ACTIVE = _pbs_ifl.MGR_CMD_ACTIVE
MGR_CMD_IMPORT = _pbs_ifl.MGR_CMD_IMPORT
MGR_CMD_EXPORT = _pbs_ifl.MGR_CMD_EXPORT
MGR_CMD_LAST = _pbs_ifl.MGR_CMD_LAST
MGR_OBJ_NONE = _pbs_ifl.MGR_OBJ_NONE
MGR_OBJ_SERVER = _pbs_ifl.MGR_OBJ_SERVER
MGR_OBJ_QUEUE = _pbs_ifl.MGR_OBJ_QUEUE
MGR_OBJ_JOB = _pbs_ifl.MGR_OBJ_JOB
MGR_OBJ_NODE = _pbs_ifl.MGR_OBJ_NODE
MGR_OBJ_RESV = _pbs_ifl.MGR_OBJ_RESV
MGR_OBJ_RSC = _pbs_ifl.MGR_OBJ_RSC
MGR_OBJ_SCHED = _pbs_ifl.MGR_OBJ_SCHED
MGR_OBJ_HOST = _pbs_ifl.MGR_OBJ_HOST
MGR_OBJ_HOOK = _pbs_ifl.MGR_OBJ_HOOK
MGR_OBJ_PBS_HOOK = _pbs_ifl.MGR_OBJ_PBS_HOOK
MGR_OBJ_JOBARRAY_PARENT = _pbs_ifl.MGR_OBJ_JOBARRAY_PARENT
MGR_OBJ_SUBJOB = _pbs_ifl.MGR_OBJ_SUBJOB
MGR_OBJ_LAST = _pbs_ifl.MGR_OBJ_LAST
SITE_HOOK = _pbs_ifl.SITE_HOOK
PBS_HOOK = _pbs_ifl.PBS_HOOK
MSG_OUT = _pbs_ifl.MSG_OUT
MSG_ERR = _pbs_ifl.MSG_ERR
PBS_MAXHOSTNAME = _pbs_ifl.PBS_MAXHOSTNAME
MAXPATHLEN = _pbs_ifl.MAXPATHLEN
MAXNAMLEN = _pbs_ifl.MAXNAMLEN
MSVR_JID_NCHARS_SVR = _pbs_ifl.MSVR_JID_NCHARS_SVR
PBS_MAXSCHEDNAME = _pbs_ifl.PBS_MAXSCHEDNAME
PBS_MAXUSER = _pbs_ifl.PBS_MAXUSER
PBS_MAXPWLEN = _pbs_ifl.PBS_MAXPWLEN
PBS_MAXGRPN = _pbs_ifl.PBS_MAXGRPN
PBS_MAXQUEUENAME = _pbs_ifl.PBS_MAXQUEUENAME
PBS_MAXJOBNAME = _pbs_ifl.PBS_MAXJOBNAME
PBS_MAXSERVERNAME = _pbs_ifl.PBS_MAXSERVERNAME
PBS_MAXSEQNUM = _pbs_ifl.PBS_MAXSEQNUM
PBS_DFLT_MAX_JOB_SEQUENCE_ID = _pbs_ifl.PBS_DFLT_MAX_JOB_SEQUENCE_ID
PBS_MAXPORTNUM = _pbs_ifl.PBS_MAXPORTNUM
PBS_MAXSVRJOBID = _pbs_ifl.PBS_MAXSVRJOBID
PBS_MAXSVRRESVID = _pbs_ifl.PBS_MAXSVRRESVID
PBS_MAXQRESVNAME = _pbs_ifl.PBS_MAXQRESVNAME
PBS_MAXCLTJOBID = _pbs_ifl.PBS_MAXCLTJOBID
PBS_MAXDEST = _pbs_ifl.PBS_MAXDEST
PBS_MAXROUTEDEST = _pbs_ifl.PBS_MAXROUTEDEST
PBS_INTERACTIVE = _pbs_ifl.PBS_INTERACTIVE
PBS_TERM_BUF_SZ = _pbs_ifl.PBS_TERM_BUF_SZ
PBS_TERM_CCA = _pbs_ifl.PBS_TERM_CCA
PBS_RESV_ID_CHAR = _pbs_ifl.PBS_RESV_ID_CHAR
PBS_STDNG_RESV_ID_CHAR = _pbs_ifl.PBS_STDNG_RESV_ID_CHAR
PBS_MNTNC_RESV_ID_CHAR = _pbs_ifl.PBS_MNTNC_RESV_ID_CHAR
PBS_AUTH_KEY_LEN = _pbs_ifl.PBS_AUTH_KEY_LEN
PBS_MAXIP_LEN = _pbs_ifl.PBS_MAXIP_LEN
SET = _pbs_ifl.SET
UNSET = _pbs_ifl.UNSET
INCR = _pbs_ifl.INCR
DECR = _pbs_ifl.DECR
EQ = _pbs_ifl.EQ
NE = _pbs_ifl.NE
GE = _pbs_ifl.GE
GT = _pbs_ifl.GT
LE = _pbs_ifl.LE
LT = _pbs_ifl.LT
DFLT = _pbs_ifl.DFLT
INTERNAL = _pbs_ifl.INTERNAL
SHUT_IMMEDIATE = _pbs_ifl.SHUT_IMMEDIATE
SHUT_DELAY = _pbs_ifl.SHUT_DELAY
SHUT_QUICK = _pbs_ifl.SHUT_QUICK
FORCE = _pbs_ifl.FORCE
NOMAIL = _pbs_ifl.NOMAIL
SUPPRESS_EMAIL = _pbs_ifl.SUPPRESS_EMAIL
DELETEHISTORY = _pbs_ifl.DELETEHISTORY
class attrl(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    next = property(_pbs_ifl.attrl_next_get, _pbs_ifl.attrl_next_set)
    name = property(_pbs_ifl.attrl_name_get, _pbs_ifl.attrl_name_set)
    resource = property(_pbs_ifl.attrl_resource_get, _pbs_ifl.attrl_resource_set)
    value = property(_pbs_ifl.attrl_value_get, _pbs_ifl.attrl_value_set)
    op = property(_pbs_ifl.attrl_op_get, _pbs_ifl.attrl_op_set)

    def __init__(self):
        _pbs_ifl.attrl_swiginit(self, _pbs_ifl.new_attrl())
    __swig_destroy__ = _pbs_ifl.delete_attrl

# Register attrl in _pbs_ifl:
_pbs_ifl.attrl_swigregister(attrl)
class attropl(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    next = property(_pbs_ifl.attropl_next_get, _pbs_ifl.attropl_next_set)
    name = property(_pbs_ifl.attropl_name_get, _pbs_ifl.attropl_name_set)
    resource = property(_pbs_ifl.attropl_resource_get, _pbs_ifl.attropl_resource_set)
    value = property(_pbs_ifl.attropl_value_get, _pbs_ifl.attropl_value_set)
    op = property(_pbs_ifl.attropl_op_get, _pbs_ifl.attropl_op_set)

    def __init__(self):
        _pbs_ifl.attropl_swiginit(self, _pbs_ifl.new_attropl())
    __swig_destroy__ = _pbs_ifl.delete_attropl

# Register attropl in _pbs_ifl:
_pbs_ifl.attropl_swigregister(attropl)
class batch_status(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    next = property(_pbs_ifl.batch_status_next_get, _pbs_ifl.batch_status_next_set)
    name = property(_pbs_ifl.batch_status_name_get, _pbs_ifl.batch_status_name_set)
    attribs = property(_pbs_ifl.batch_status_attribs_get, _pbs_ifl.batch_status_attribs_set)
    text = property(_pbs_ifl.batch_status_text_get, _pbs_ifl.batch_status_text_set)

    def __init__(self):
        _pbs_ifl.batch_status_swiginit(self, _pbs_ifl.new_batch_status())
    __swig_destroy__ = _pbs_ifl.delete_batch_status

# Register batch_status in _pbs_ifl:
_pbs_ifl.batch_status_swigregister(batch_status)
class batch_deljob_status(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    next = property(_pbs_ifl.batch_deljob_status_next_get, _pbs_ifl.batch_deljob_status_next_set)
    name = property(_pbs_ifl.batch_deljob_status_name_get, _pbs_ifl.batch_deljob_status_name_set)
    code = property(_pbs_ifl.batch_deljob_status_code_get, _pbs_ifl.batch_deljob_status_code_set)

    def __init__(self):
        _pbs_ifl.batch_deljob_status_swiginit(self, _pbs_ifl.new_batch_deljob_status())
    __swig_destroy__ = _pbs_ifl.delete_batch_deljob_status

# Register batch_deljob_status in _pbs_ifl:
_pbs_ifl.batch_deljob_status_swigregister(batch_deljob_status)
class ecl_attrerr(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ecl_attribute = property(_pbs_ifl.ecl_attrerr_ecl_attribute_get, _pbs_ifl.ecl_attrerr_ecl_attribute_set)
    ecl_errcode = property(_pbs_ifl.ecl_attrerr_ecl_errcode_get, _pbs_ifl.ecl_attrerr_ecl_errcode_set)
    ecl_errmsg = property(_pbs_ifl.ecl_attrerr_ecl_errmsg_get, _pbs_ifl.ecl_attrerr_ecl_errmsg_set)

    def __init__(self):
        _pbs_ifl.ecl_attrerr_swiginit(self, _pbs_ifl.new_ecl_attrerr())
    __swig_destroy__ = _pbs_ifl.delete_ecl_attrerr

# Register ecl_attrerr in _pbs_ifl:
_pbs_ifl.ecl_attrerr_swigregister(ecl_attrerr)
class ecl_attribute_errors(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    ecl_numerrors = property(_pbs_ifl.ecl_attribute_errors_ecl_numerrors_get, _pbs_ifl.ecl_attribute_errors_ecl_numerrors_set)
    ecl_attrerr = property(_pbs_ifl.ecl_attribute_errors_ecl_attrerr_get, _pbs_ifl.ecl_attribute_errors_ecl_attrerr_set)

    def __init__(self):
        _pbs_ifl.ecl_attribute_errors_swiginit(self, _pbs_ifl.new_ecl_attribute_errors())
    __swig_destroy__ = _pbs_ifl.delete_ecl_attribute_errors

# Register ecl_attribute_errors in _pbs_ifl:
_pbs_ifl.ecl_attribute_errors_swigregister(ecl_attribute_errors)
PREEMPT_METHOD_LOW = _pbs_ifl.PREEMPT_METHOD_LOW
PREEMPT_METHOD_SUSPEND = _pbs_ifl.PREEMPT_METHOD_SUSPEND
PREEMPT_METHOD_CHECKPOINT = _pbs_ifl.PREEMPT_METHOD_CHECKPOINT
PREEMPT_METHOD_REQUEUE = _pbs_ifl.PREEMPT_METHOD_REQUEUE
PREEMPT_METHOD_DELETE = _pbs_ifl.PREEMPT_METHOD_DELETE
PREEMPT_METHOD_HIGH = _pbs_ifl.PREEMPT_METHOD_HIGH
class preempt_job_info(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    job_id = property(_pbs_ifl.preempt_job_info_job_id_get, _pbs_ifl.preempt_job_info_job_id_set)
    order = property(_pbs_ifl.preempt_job_info_order_get, _pbs_ifl.preempt_job_info_order_set)

    def __init__(self):
        _pbs_ifl.preempt_job_info_swiginit(self, _pbs_ifl.new_preempt_job_info())
    __swig_destroy__ = _pbs_ifl.delete_preempt_job_info

# Register preempt_job_info in _pbs_ifl:
_pbs_ifl.preempt_job_info_swigregister(preempt_job_info)
RESV_NONE = _pbs_ifl.RESV_NONE
RESV_UNCONFIRMED = _pbs_ifl.RESV_UNCONFIRMED
RESV_CONFIRMED = _pbs_ifl.RESV_CONFIRMED
RESV_WAIT = _pbs_ifl.RESV_WAIT
RESV_TIME_TO_RUN = _pbs_ifl.RESV_TIME_TO_RUN
RESV_RUNNING = _pbs_ifl.RESV_RUNNING
RESV_FINISHED = _pbs_ifl.RESV_FINISHED
RESV_BEING_DELETED = _pbs_ifl.RESV_BEING_DELETED
RESV_DELETED = _pbs_ifl.RESV_DELETED
RESV_DELETING_JOBS = _pbs_ifl.RESV_DELETING_JOBS
RESV_DEGRADED = _pbs_ifl.RESV_DEGRADED
RESV_BEING_ALTERED = _pbs_ifl.RESV_BEING_ALTERED
RESV_IN_CONFLICT = _pbs_ifl.RESV_IN_CONFLICT

def __pbs_errno_location():
    return _pbs_ifl.__pbs_errno_location()

def __pbs_server_location():
    return _pbs_ifl.__pbs_server_location()

def pbs_asyrunjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_asyrunjob(arg1, arg2, arg3, arg4)

def pbs_asyrunjob_ack(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_asyrunjob_ack(arg1, arg2, arg3, arg4)

def pbs_alterjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_alterjob(arg1, arg2, arg3, arg4)

def pbs_asyalterjob(c, jobid, attrib, extend):
    return _pbs_ifl.pbs_asyalterjob(c, jobid, attrib, extend)

def pbs_confirmresv(arg1, arg2, arg3, arg4, arg5):
    return _pbs_ifl.pbs_confirmresv(arg1, arg2, arg3, arg4, arg5)

def pbs_connect(arg1):
    return _pbs_ifl.pbs_connect(arg1)

def pbs_connect_extend(arg1, arg2):
    return _pbs_ifl.pbs_connect_extend(arg1, arg2)

def pbs_disconnect(arg1):
    return _pbs_ifl.pbs_disconnect(arg1)

def pbs_manager(arg1, arg2, arg3, arg4, arg5, arg6):
    return _pbs_ifl.pbs_manager(arg1, arg2, arg3, arg4, arg5, arg6)

def pbs_default():
    return _pbs_ifl.pbs_default()

def pbs_deljob(arg1, arg2, arg3):
    return _pbs_ifl.pbs_deljob(arg1, arg2, arg3)

def pbs_deljoblist(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_deljoblist(arg1, arg2, arg3, arg4)

def pbs_geterrmsg(arg1):
    return _pbs_ifl.pbs_geterrmsg(arg1)

def pbs_holdjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_holdjob(arg1, arg2, arg3, arg4)

def pbs_loadconf(arg1):
    return _pbs_ifl.pbs_loadconf(arg1)

def pbs_locjob(arg1, arg2, arg3):
    return _pbs_ifl.pbs_locjob(arg1, arg2, arg3)

def pbs_movejob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_movejob(arg1, arg2, arg3, arg4)

def pbs_msgjob(arg1, arg2, arg3, arg4, arg5):
    return _pbs_ifl.pbs_msgjob(arg1, arg2, arg3, arg4, arg5)

def pbs_relnodesjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_relnodesjob(arg1, arg2, arg3, arg4)

def pbs_orderjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_orderjob(arg1, arg2, arg3, arg4)

def pbs_rerunjob(arg1, arg2, arg3):
    return _pbs_ifl.pbs_rerunjob(arg1, arg2, arg3)

def pbs_rlsjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_rlsjob(arg1, arg2, arg3, arg4)

def pbs_runjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_runjob(arg1, arg2, arg3, arg4)

def pbs_selectjob(arg1, arg2, arg3):
    return _pbs_ifl.pbs_selectjob(arg1, arg2, arg3)

def pbs_sigjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_sigjob(arg1, arg2, arg3, arg4)

def pbs_statfree(arg1):
    return _pbs_ifl.pbs_statfree(arg1)

def pbs_delstatfree(arg1):
    return _pbs_ifl.pbs_delstatfree(arg1)

def pbs_statrsc(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statrsc(arg1, arg2, arg3, arg4)

def pbs_statjob(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statjob(arg1, arg2, arg3, arg4)

def pbs_selstat(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_selstat(arg1, arg2, arg3, arg4)

def pbs_statque(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statque(arg1, arg2, arg3, arg4)

def pbs_statserver(arg1, arg2, arg3):
    return _pbs_ifl.pbs_statserver(arg1, arg2, arg3)

def pbs_statsched(arg1, arg2, arg3):
    return _pbs_ifl.pbs_statsched(arg1, arg2, arg3)

def pbs_stathost(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_stathost(arg1, arg2, arg3, arg4)

def pbs_statnode(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statnode(arg1, arg2, arg3, arg4)

def pbs_statvnode(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statvnode(arg1, arg2, arg3, arg4)

def pbs_statresv(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_statresv(arg1, arg2, arg3, arg4)

def pbs_stathook(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_stathook(arg1, arg2, arg3, arg4)

def pbs_get_attributes_in_error(arg1):
    return _pbs_ifl.pbs_get_attributes_in_error(arg1)

def pbs_submit(arg1, arg2, arg3, arg4, arg5):
    return _pbs_ifl.pbs_submit(arg1, arg2, arg3, arg4, arg5)

def pbs_submit_resv(arg1, arg2, arg3):
    return _pbs_ifl.pbs_submit_resv(arg1, arg2, arg3)

def pbs_delresv(arg1, arg2, arg3):
    return _pbs_ifl.pbs_delresv(arg1, arg2, arg3)

def pbs_terminate(arg1, arg2, arg3):
    return _pbs_ifl.pbs_terminate(arg1, arg2, arg3)

def pbs_modify_resv(arg1, arg2, arg3, arg4):
    return _pbs_ifl.pbs_modify_resv(arg1, arg2, arg3, arg4)

def pbs_preempt_jobs(arg1, arg2):
    return _pbs_ifl.pbs_preempt_jobs(arg1, arg2)

